### ISSUE TITLE
UE4 v4.6.1: Nothing Builds during Test play.

### ISSUE THREAD

**Issue by Flam1ngDem0n** [ryanjon2040/RTS-Community-Project#13]
I am currently running the RTS Community Project on Unreal Engine 4, Engine Version 4.6.1 and I have run into a couple of things that are causing issues.

First of all, the BP_ConstructionManager seems to have a "Create Event" node that apparently needs a the user to choose a function from the drop down list within this node. There are two visible options to choose from from the said drop down list.
A): FinishConstruction(Proxy)
or
B): OnConstructionComplete(Proxy)

Both of which I don't know what the do at the current time. And from what I can tell choosing either and then play testing, then stop play testing will reset this node so that when you click "Play" in the editor; you are asked to fix the same error again. Before continuing to play test again.

![error](https://cloud.githubusercontent.com/assets/2099250/6050200/f7b3adbc-ac7a-11e4-9e42-78c2b8d30f22.png)

![error_2](https://cloud.githubusercontent.com/assets/2099250/6050201/f7b3f146-ac7a-11e4-8fea-47e3a7b387bd.png)

The second issue I have run into while play testing is that when clicking to place a structure/building seems to do nothing. Well, except create (in my case) a Barracks Proxy object that can be seen in the Scene Outliner.

![building_error_1](https://cloud.githubusercontent.com/assets/2099250/6050240/41a78452-ac7b-11e4-8dfe-d6719559f5ad.png)

![building_error_2](https://cloud.githubusercontent.com/assets/2099250/6050241/41a87506-ac7b-11e4-9d79-8ff56236b761.png)

What are causing these issues to happen and how do I fix them?

Thanks.

**Comment by UE4Thommie** [comment]
Hi,

I completely forgot about those problems, i fixed them when 4.6 came out but since it was a messy workaround i didn't push it. Not quite sure what i did to solve all of those problems but i was planning on pushing a new version (for 4.6.1) this weekend with all this fixed and more :)

**Comment by Flam1ngDem0n** [comment]
Is there a way to work around it or even fix it for the time being? If so, how would I go about doing so?

**Comment by UE4Thommie** [comment]
The following images should provide enough guidance to fixing it (note that in addition to attaching some broken pins you need to create the new custom event in the eventgraph)

![1](https://cloud.githubusercontent.com/assets/7030276/6067527/78f5121c-ad75-11e4-83b9-8931146fc069.png)
![2](https://cloud.githubusercontent.com/assets/7030276/6067530/78fc9992-ad75-11e4-86f8-cc8c1a0cb5e4.png)
![3](https://cloud.githubusercontent.com/assets/7030276/6067528/78f77214-ad75-11e4-9377-299df0217fc9.png)
![4](https://cloud.githubusercontent.com/assets/7030276/6067529/78fd0666-ad75-11e4-978c-805d5a6a9535.png)

**Comment by Flam1ngDem0n** [comment]
I see that you have a node in the second screenshot that refers to "BindConstructionCompleted". What input(s) did you choose for this node?

**Comment by Flam1ngDem0n** [comment]
Another question, would you be willing to show me your side panel on the left? As I don't know what you currently are using or have created.

Thanks.

**Comment by UE4Thommie** [comment]
Hi,

I just created a custom event (Bind Construction Completed) in the event graph with 1 BP_Construction_Proxy input called Proxy. I hope this helps, if you still need more info i'd be happy to help.

**Comment by Flam1ngDem0n** [comment]
Ok so I got that, but there is (what seems to be) a custom Function you've created called "Bind Construction Completed". It's shown in the third image down from the top. It is located between "Cast To BP_Construction Proxy" and the "Add" nodes.

Is that in fact custom function or am I just missing something?

Thanks.

**Comment by Flam1ngDem0n** [comment]
Also, I am having an problem within the Event Graph. Here is a screenshot of the matter:

![2015-02-06_1301](https://cloud.githubusercontent.com/assets/2099250/6086593/5eef3510-ae00-11e4-8c22-295e126d20ab.png)

**Comment by Flam1ngDem0n** [comment]
Also for Documentation purposes, here is a heads up on the list/screenshot of both Warnings and errors I am encountering right now.

![2015-02-06_1305](https://cloud.githubusercontent.com/assets/2099250/6086694/222d339c-ae01-11e4-86ac-09703b008237.png)

**Comment by UE4Thommie** [comment]
It seems to me you've changed a few things. To answer your questions:

Ok so I got that, but there is (what seems to be) a custom Function you've created called "Bind Construction Completed".
In the event graph i right clicked and created an event called BindConstructionCompleted with Proxy as BP_Construction_Proxy as input. From Proxy i dragged Bind Event to ConstructionCompleted and then attached OnConstructionCompleted to it. So i'm not calling a function but an event.

Also, from your pictures i can see you're not using Proxy (as BP_Construction_Proxy) but the Construction manager as a target for binding the event. So you can remove the custom created event dispatcher in the Construction Manager. Aside from that you've changed the parameter for OnConstructionCompleted to be BP_Construction_Manager instead of BP_Construction_Proxy.

This should solve 3 of your 4 errors. As for the second error, it seems you've disconnected a reroute node, you need to connect or delete it.

**Comment by Flam1ngDem0n** [comment]
Based on your screenshots, I am doing the same exact thing in the Event Graph. I created a new custom event, named it "BindConstructionCompleted" and set it's Input to use the "BP_ConstructionProxy".

"Also, from your pictures i can see you're not using Proxy (as BP_Construction_Proxy) but the Construction manager as a target for binding the event."

 What is this in reference to? If you are talking about within the Event Graph then I simply have it set to the same as what yours shows in the screenshot of your Event Graph. Seen here:

![78fc9992-ad75-11e4-86f8-cc8c1a0cb5e4](https://cloud.githubusercontent.com/assets/2099250/6092796/7a674a88-aeac-11e4-94ca-40f891c23db1.png)

As shown in the screenshot of your Event Graph, your "Finish Construction" node is targeted to the "BP_ConstructionManager".

Also, I still don't understand where you are getting the node that is sitting in between "Cast To BP_ConstructionProxy" and the "ADD" node in this screenshot. It's shown as "Bind Construction Com Completed". Seen here:

![78f77214-ad75-11e4-9377-299df0217fc9](https://cloud.githubusercontent.com/assets/2099250/6092810/014a92d0-aead-11e4-8673-e65742f225d4.png)

Can you please tell me where you got that node, or if you created it what parameters were used to do so?

**Comment by Flam1ngDem0n** [comment]
Something I just noticed about the Node called "Bind Construction Completed", lt looks like it's a custom function that you created that I don't have within the project files.

Can you please verify?

Thanks.

**Comment by UE4Thommie** [comment]
Hi,

I don't have much time today so i've just uploaded a working version for 4.6.1 https://github.com/UE4Thommie/RTS-Community-Project/

i'll try and answer/explain more tomorrow if you still have any questions left.

And  "Bind Construction Completed" is the event i created in the event graph

**Comment by Flam1ngDem0n** [comment]
Ok, looks like with your recent update that you uploaded it is working now.

Thanks for the help!
